### PR TITLE
Interpolation Module

### PR DESCRIPTION
**Pull request by Jonhas**
Refactored Interpolation module that follows the new requirements. The module modifies the raw object in place and also returns a dictionary of information, such as {"Interpolation": info_here}}, where we can then add to a general dictionary, which can then be dumped for a json file.

### CODE REVIEW

**Review by F-said — APPROVED** [review]
Code ready to merge. Just need to resolve conflict with interp.py & gitignore.

Planning on making the following resolutions, let me know if they follow the intent of the PR @Jonhas :

**interp.py**

will manually add in interp.py to override delete in dev-feature-segment 

**gitignore**
combining changes into
```
# IDE specific 
.idea
.vscode

# OS specific 
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
```

**Comment by georgebuzzell** [comment]
Wonderful work, @Jonhas, and very much appreciated!

Please just confirm the minor gitignore change @F-said suggested.

@F-said thank you for reviewing!!

**Comment by Jonhas** [comment]
@F-said that would work perfectly, thank you for reviewing

**Comment by georgebuzzell** [comment]
Excellent, @Jonhas and @F-said !

**Pull request merged**
