### PR TITLE
FASTER to get bad channels in BIDS data

### LINKED ISSUE #25: Feature-badchans
Feature-badchans
-auto-detect and remove bad channels (those that are “noisy” for a majority of the recording)
-write to annotations file to indicate which channels were detected as bad, what metrics indicated they were bad, and whether they were removed

### PR DESCRIPTION
**Pull request by F-said**
- Automatic bad channel detection using FASTER to resolve #25

flake8 fails on imported file `faster.py.` Does this matter if the file is imported from an external source?

### CODE REVIEW

**Comment by F-said** [comment]
Cleaned up PR from previous https://github.com/NDCLab/baseEEG/pull/73

**Comment by georgebuzzell** [comment]
@F-said so great!!

Sorry, should have commented before about flake8 failure. I think it depends. If it is a standalone function we are not touching in any way, then prob ok goes it to fail, but, as it appears in this case, we are modifying the code itself, then I think it should be brought into compliance.  Agree/disagree?

**Comment by F-said** [comment]
@georgebuzzell agreed. Will make another commit fixing flake8 errors.

**Comment by F-said** [comment]
Reflecting @SDOsmany code-review: rerun method on non-epoched data.

**Comment by SDOsmany** [comment]
@F-said for the faster_bad_channels, it says for the epochs parameter that it has to be an instance of Epochs, so I don't think is gonna let you pass the raw data.

**Comment by F-said** [comment]
@SDOsmany good take on `faster_bad_channels`, it strictly takes in epochs. Building on your idea we could also code up a cross-validation approach, so that bad channels aren't set for just hard-coded time ranges:

We could exhaustively create unique epoch data on some set of time ranges and use each dataset to find bad channels using `faster_bad_channels`. Like you wrote we could possibly calculate if bad epochs surpass some threshold of the channel. Each bad channel result would be stored. 

Then we could use another threshold where if a specific channel appears some percent of times out of all generated results, say 60%, then it would finally be classified as "bad."

Let me know what you think! Also is the described approach violating any scientific/statistical norms @georgebuzzell ?

**Comment by SDOsmany** [comment]
@F-said sorry I'm not sure what you mean by this "so that bad channels aren't set for just hard-coded time ranges".  

The good thing that I see from a method like this(if possible) is that the marking threshold could be up to the user, and they can decide if to accept for example 80% if the channel instead of 60%, etc. and the default would be whatever people think is best

**Comment by F-said** [comment]
@SDOsmany Sure, so currently the implementation of `faster_bad_channels()` uses epochs -0.2 seconds before an event and 0.5 sec after an event. Maybe if we iterate on a set of time ranges ((-0.2, 0.5), (-0.3, 0.6), (-0.4, 0.7), ...) and detect bad channels on all time ranges, we could then similarly apply some threshold where if a channel appears as "bad" for 80% (or some set user number) of time-ranges, then it will finally be removed.

**Comment by georgebuzzell** [comment]
@F-said and @SDOsmany I went back and checked the paper on FASTER and can confirm that the first step of FASTER runs on continuous data. If you look at the FASTER code you all pulled in, on lines 97-100 you can see that they actually concatenation the epochs into one long time series before running the analyses. So, you would just want to modify the code so that instead of expecting epochs as input, only continuous data is expected. That should work fine, but let me know if I can provide more clarity here about what I mean.

One thing to note, is that I am unsure how much this py instantiaton of FASTER has been tested in general, so we will likely want to do more tests for this feature. Relatedly, it is unclear to me if the py code is accounting for channel location or not, if not, we will need to add that in. But for now, if you are able to just get the code running on continuous data that would be an excellent first step.

Thanks!

**Comment by SDOsmany** [comment]
@F-said I think we can also discuss doing what George mention during our meeting tomorrow at 11 am

**Comment by georgebuzzell** [comment]
@F-said and @SDOsmany I am closing this pull request. Please modify the code based on my comment above before opening a new pull request. Thank you!

**Pull request closed without merging**
