### PR TITLE
Segmentation Module

### PR DESCRIPTION
**Pull request by Jonhas**
Simple segmentation module that follows the new requirements. The module returns an epochs object alongside a dictionary of information, such as {"Segmentation": info_here}}, where we can then add to a general dictionary, which can then be dumped for a json file.

### CODE REVIEW

**Review by F-said — APPROVED** [review]
Code ready to merge. Github has a small merge conflict in the gitignore. @Jonhas Would it be ok if I resolve using:

```
# IDE specific 
.vscode

# OS specific 
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db
```

**Comment by georgebuzzell** [comment]
Thank you, @Jonhas! looks great! Please just confirm the resolution for gitignore that @F-said mentioned

**Comment by Jonhas** [comment]
@F-said that would work perfectly

**Comment by georgebuzzell** [comment]
Thank you @Jonhas and @F-said !!

**Pull request merged**
