### PR TITLE
Update Jupyter to JupyterLab 

### PR DESCRIPTION
**Pull request by DMRoberts**
Update Jupyter to JupyterLab within the Conda environment. JupyterLab also includes Juypyter, but seems to allow for a bit more interactive plotting. I had also formatted the Docker readme as a markdown document.

### CODE REVIEW

**Comment by georgebuzzell** [comment]
@DMRoberts Thanks for this PR!

The Docker builds runs fine. However, it is unclear how to connect it to jupyterHub/JupyterLab?

I think we previously used this to connect: jupyter notebook --ip 0.0.0.0 --no-browser --allow-root

Is something similar needed here? Sorry, likely a user error... Would you mind updating the readme with further detail? I also see that our current readme's detail on traditional jupyterHub is also now lacking (I think the line above got cut at some point?)

@F-said please take a look and/or comment as well!

**Comment by DMRoberts** [comment]
@georgebuzzell connecting is listed under the final header in the readme, titled **'While in virtual machine, run the following to link ports:'**

I'n not sure about your comment about " our current readme's detail on traditional jupyterHub is also now lacking", I just checked and I don't think I had removed anything related to JupyterHub in the readme? For a traditional Jupyter notebook, the person would just use 'jupyter notebook' instead of 'jupyter lab'.

**Comment by georgebuzzell** [comment]
Thanks, @DMRoberts! Apologies, you are correct that I was misreading the readme file.

That said, I tried connecting to ports but get a command not found error. Another user error on my end?

image

**Comment by DMRoberts** [comment]
@georgebuzzell It sound like you didn't activate the Conda environment, try the following when you enter the Docker container before running the Jupyter command. This isn't anything I changed but is related to when we moved from PIP / requirements.txt to Conda for managing the environment dependencies. There may be some way to have the Conda environment already activated in the Docker image.

```
source activate
source activate mne
```

**Review by georgebuzzell — APPROVED** [review]
tested. runs.

Great work, @DMRoberts !!

**Pull request merged**
