### PR TITLE
Dev feature filter yanbin

### PR DESCRIPTION
**Pull request by yanbin-niu**
#24 

Please copy the data into "raw_data/eegmatchingpennies"

Moreover, I edited it a little:
1. added try except part;
2. renamed function into "baseeeg_preprocessing_filter" and file name into "preprocessing_filter";

### CODE REVIEW

**Comment by georgebuzzell** [comment]
@yanbin-niu Thank you for making these pull requests! 

I tried running in native python and get an error that there is "No module named 'matplotlib' "

Perhaps this is a user error on my end?

Please advise. I am running using the docker file included as part of your pul request branch.

I will hold off on reviewing the other PR until I hear back, as I may be doing something wrong on my end that would impact both PRs.

**Comment by yanbin-niu** [comment]
@georgebuzzell 

1. did you build a new image based on the dockerfile?
2. After you run the container - "docker run --rm -it -v $(PWD):/projects -w /projects -p 5000:8888 ndceeg:v1 bash", you should: 1. source activate; 2. conda activate mne. Making sure mne is activated should solve the issue.

**Comment by georgebuzzell** [comment]
Thanks @yanbin-niu !

Yes, I did build the new image. However, I did not run the additional lines of code. Did I happen to miss those in the readme? If those steps are not in the readme, could you please add those additional steps to the readme and initate a new PR, please? I think this was not detected previously, for your PR of the new docker file, as I only built and ran, without running any additional test code in the container.

**Comment by yanbin-niu** [comment]
Last Saturday, I thought we decided on that I make a PR for the dockerfile and environment.yml; and Jonhas make a PR for the readme (alongside the volume mount stuff). But, of course! I can make a new PR for these two new command lines if you think the readme should be updated as soon as possible:)

**Comment by yanbin-niu** [comment]
@georgebuzzell I just saw Dan committed a PR related to readme. would you please review that first? then I will make a PR based on that one.

**Comment by georgebuzzell** [comment]
@yanbin-niu yes, you are correct. Sorry, I see the confusion now! OK, don't worry about a new PR, I will add these pieces in to the readme as I re-test this PR. Thank you!!

**Comment by yanbin-niu** [comment]
@georgebuzzell Thank you!!

**Pull request merged**
