### PR TITLE
Create pylint.yml

### PR DESCRIPTION
**Pull request by yanbin-niu**
CI test

### CODE REVIEW

**Comment by georgebuzzell** [comment]
@yanbin-niu this is great! Thank you! I made a minor change to only check python version 3.9, since that is the version in our docker.

@F-said can you please review this PR from @yanbin-niu? This is to add the CI code to run flake8 (to check for consistency with Pep8), triggered on any push/pull to a given branch. We want to push this to dev and main, that way, whenever someone forks off of dev in the future, they will have this ci code in their branch, and when they do a push/pr it will run the tests. The idea is that for a PR to be approved, all tests will need to pass. Please note that it is ok that the tests on this PR "failed" as this PR is for the CI itself, not the code it is "testing" :)

Please note that, right now, the CI triggers on any push, even if a .py file is not part of the commit. that is fine for now, but it would be ideal if the ci was conditional to only run when a .py file changes. @F-said let us know if you have any insights in that direction. But again, that is not a reason to not accept this pr.

**Review by georgebuzzell — APPROVED** [review]

**Comment by georgebuzzell** [comment]
@F-said please take a look when you can. :)

**Review by F-said — APPROVED** [review]
To target only files that the programmer plans on committing, perhaps we can integrate flake8 with [pre-commit](https://flake8.pycqa.org/en/latest/user/using-hooks.html?highlight=git) hooks in the future. This will run the linter any py file the user plans on pushing.

**Comment by georgebuzzell** [comment]
@F-said your suggestion of integrating flake8 with pre-commit hooks sounds great! How hard would it be to set this up? and, are there any downsides?

@yanbin-niu curious of your input here too, of course!

**Comment by yanbin-niu** [comment]
@georgebuzzell I took a look at this pre-commit hooks (Thank you @F-said  for bringing me the idea!!!). Unfortunately, I think it may not work, though not fully understand how it works. My understanding is, @georgebuzzell  you want the IC not to be triggered at all if no .py files are changed. 

Also, my understanding about git hooks is, " it does linter (flake8) before submission to code review" and pre-commit can exclude some files which will not be passed to flake8. (@F-said  correct me if I misunderstand). That is to say, this function overlaps with that of gh Action which is what we currently use.

How the gh Action works is, whenever there is an action/actions (e.g., PR or push), the gh Action will do something, kind of like a container (in our case, set up an ubuntu environment, checkout the rep, install python and flake8, and run flake8). In other words, the gh Action will run regardlessly. Given the gh Action will checkout the whole branch, I just did not figure out how to find which file has been changed.

Early on I was thinking about this. I was thinking, after setting up the ubuntu environment, maybe maybe there is a way to get the info of files that have been changed, like commit reference or some other thing (but still did not figure out T_T). I checked other's repositories, but still did not find anything related to this. I will keep this in mind! Also, @F-said if you find anything that might work, please please let me know. And I am also happy to discuss further!

**Comment by georgebuzzell** [comment]
@yanbin-niu thank you for this detailed follow up!! If there is not an easy, immediate solution so that flake8 only runs when a .py file is created, then i say we dont worry about it for now. :) But I really apprecaite the efforts here!

**Pull request merged**
