### PR TITLE
Main pipeline for driver code 

### LINKED ISSUE #108: create issue template based on tags for standardization
Create templates for at min:

- bugs
- enhancements
- hpc

will have section for "done" description per #81

### PR DESCRIPTION
**Pull request by F-said**
Closes #108 

### changes

- json from gist created
- looped pipeline calls functions
- established directory structure for pipeline modules (and future sub-packages like post-processesing)
- pipeline writes output_json file using code from dictCollat (to be merged) 

Discussion of directory found in #120

### CODE REVIEW

**Comment by F-said** [comment]
Integration plan for setting up future development

1. merge complete functions from feature branches into dev
2. merge driver and pipeline package directory structure once approved
3. integrate complete features with the directory structure to shape future development 

Modifying documentation at the end

**Comment by F-said** [comment]
linter checks are a bit inaccurate for this file since functions are not *explicitly* used

**Review by yanbin-niu — COMMENTED** [review]
looks great to me.

**Comment by SDOsmany** [comment]
looks great @F-said great work!

**Review by SDOsmany — COMMENTED** [review]
I don't see any issues with it.

**Comment by F-said** [comment]
place all steps in one module

**Pull request closed without merging**
