### PR TITLE
FASTER algorithm to detect bad channels

### LINKED ISSUE #25: Feature-badchans
Feature-badchans
-auto-detect and remove bad channels (those that are “noisy” for a majority of the recording)
-write to annotations file to indicate which channels were detected as bad, what metrics indicated they were bad, and whether they were removed

### PR DESCRIPTION
**Pull request by F-said**
- Automatic bad channel detection using FASTER to resolve #25 

Imported `faster.py` file misses 2 flake8 checks, multiple-indent on lines 81 & 231 in evading my fix. Does anyone have any insight on how to make these lines code pep compliant? Or does this need to be linted if the gist is imported from an external package?

### CODE REVIEW

**Comment by F-said** [comment]
Need to squash commits

**Comment by georgebuzzell** [comment]
@F-said Would there be any value in NOT squashing commits? That is, do you see any possible value, for the research environment we are in and credit for work, to not squash commits? Or, is it indeed better to squash in all cases?

**Comment by F-said** [comment]
@georgebuzzell most of the commits I made were extraneous, pardon me if it pinged your email endlessly. Namely the commits where everyone's work was applied to this branch, and the commits where I was using the flake8 on GitHub to lint my code. 

To show the relevant changes to the bad-chans code and the original "faster.py" code, I could manually place them in the comments of the new PR I opened.

**Comment by georgebuzzell** [comment]
@F-said let's discuss this at the meeting today? Can u please create today's agenda and add this and any other items you think are useful to discuss?

And no need for apologies here. If I ever get annoyed with notifications of people working hard and doing great work, then please slap me! :)

**Pull request closed without merging**
