### PR TITLE
Dev feature ica yanbin

### PR DESCRIPTION
**Pull request by yanbin-niu**
The ica feature with adjust algorithm integrated.

The algorithm was adapted from eeglab/matlab version ADJUST.

Other than the algorithm, some specifications in this PR:
1. it uses `get_components` as the mixing matrix (without integrating the whitening);
2. it uses montage values to calculate distances among electrodes (go through a scaling);
3. it adjusts the angular calculation based on MNE coordinates;

The mixing matrix and coordinates would be changed in the future.

### CODE REVIEW

**Comment by DMRoberts** [comment]
@yanbin-niu I can look at this in more detail this week, but one initial comment:

I believe we can get the montage associated with a recording via `raw.get_montage()`. This value may not necessarily be set (`None`), but I think we should likely set the montage when initially loading the file, and then just read it from the raw file in the ICA step. This is because the montage could be a set of digitized electrodes, which won't necessarily have a string representation to pass to `make_standard_montage`.

**Comment by yanbin-niu** [comment]
@DMRoberts Thanks Dan for taking a look at this. `raw.get_montage()` is similar to what I did early on (read from `raw.info['chs']`). I think there might be a problem to do this. You said that "the distance measure, it won't matter if we used the montage coordinates or the raw.info coordinates, since the relative positions between electrodes will be the same". But I think it matters, since `raw.info` went through extra scaling and the scaling matrix is not identical to x, y and z. I remember the scaling matrix is [1, 0.98xxx, 0.0xxxx] (for x, y and z respectively). This is why x and y have nearly identical values as in the montage object, but the Z values are different (as you mentioned). This means, after scaling disproportionally, the z axis's distances would be underestimated. Does this make sense? it's like: `d = sqrt (x^2 + y^2 + z^2)`; `d1 = sqrt ((ax)^2 + (by)^2 + (cz)^2)`. They are different. But, the montage coordinates only go through identical scaling for x, y and z (0.010827040864626665). it's like: `d2 =  sqrt ((ax)^2 + (ay)^2 + (az)^2)  = sqrt(a)*d`. So, using the montage coordinates should be better (should not be a problem for Adjust's distance ranking and faster's `polyval`).

**Comment by yanbin-niu** [comment]
@DMRoberts Just get back to home and double checked. Sorry my memory is not accurate. The trans is here:

```
# apply rotation & scale
out_pts = np.dot(pts, trans[:3, :3].T)
# apply translation
if move:
    out_pts += trans[:3, 3]
```
https://github.com/mne-tools/mne-python/blob/main/mne/transforms.py#L216

where the `trans` is 
[1. 0. 0. 0.]
[0.         0.99515939 0.09827382 0.00302442]
[ 0.         -0.09827382  0.99515939  0.03507779]
[0. 0. 0. 1.]

so, x_after = x_before
y_after = (y_before * 0.99515939 + z_before * 0.09827382) + 0.00302442
z_after = (y_before * -0.09827382 + z_before * 0.99515939) + 0.03507779

So, you are right, the relative positions should remain largely the same. (Sorry for the last comment. totally forget where I got that impression.)

**Comment by DMRoberts** [comment]
Hey @yanbin-niu,

I'm just writing out my current understanding - I think the various components we have are the following. I hadn't realized until your last couple of messages that when the montage is converted from an 'unknown' to 'head' reference frame as it is loaded into the raw EEG object, there is also a small transformation that is not constant across the axes.

1. The .SFP text file containing the montage locations for the standard montages.

2. The montage loaded via mne.channels.make_standard_montage(). I believe the values in the .SFP file are scaled from centimeters to meters, and then scaled relative to the slightly adjusted head size in MNE. From the combinations of the two scalings, the MNE coordinate values are now 0.010827 * the coordinates in the SFP file. This scaling seems to be constant across all 3 dimensions. This montage doesn't have a reference frame applied: `mne.channels.make_standard_montage('GSN-HydroCel-129').dig` has 'unknown frame' listed in the right columns.

At this point the MNE coordinates differ from EEGLAB, which converts the .SFP file into a different coordinate system, where the the Y axis in the .SFP becomes X, the X axis in the .SFP becomes Y, and the resulting Y axis is flipped, and doesn't otherwise scale the data.

3. If a montage has been applied to the EEG raw object, this can be accessed via raw.get_montage(). I had originally thought that this just maps the montage that had been applied to the EEG raw object to a head-frame, but otherwise left the data unchanged. This change of reference frame is what I had mentioned before, where the Z-dimension was obviously changed. I hadn't realized until I read your previous message that there seems to be an additional transformation that is not constant across the 3-axes when the montage is loaded into the data, though the difference between the axes is relatively small as you mentioned.

4. The channel positions can be extracted from the EEG raw object, via `raw._get_channel_positions()`, which is the same data as contained in `raw.info['chs']`. The reference frame seems to be shifted from the loaded montage, but with no other transformation.

Doing some tests, the channel distances from a loaded montage ` raw.get_montage() `, are identical to those from the channel positions `raw.get_channel_positions() `. The channel distances from the montage prior to being applied to the EEG object are slightly different, but the difference is small, the largest absolute difference in channel distance between the standard montage and montage after being applied to the EEG data is 5.01127253582645e-09.

My primary reasoning around not using the mne.channels.make_standard_montage() function, is that I'm not sure if that function can be used if a dataset has non-standard electrode locations, or if the electrodes have been digitized and need to be loaded from a file specific to each participant. In that case, we may want to add the montage in an earlier step, and just read it from the raw object when running the ICA.

The code I used to test this:

```
import mne
import numpy as np

def get_channel_distances(channel_positions):
    num_channels = channel_positions.shape[0]
    distance = np.zeros([num_channels, num_channels])
    for c1 in range(num_channels):
        for c2 in range(num_channels):
            distance[c1, c2] = np.linalg.norm(channel_positions[c1,:] - channel_positions[c2,:])
    return distance

def extract_positions_from_montage(montage):
    num_channels = len(montage.get_positions()['ch_pos'])
    montage_positions = np.empty([num_channels, 3])
    for idx, c_name in enumerate(montage.ch_names):
        montage_positions[idx, :] = montage.get_positions()['ch_pos'][c_name]
    return montage_positions

# simulate an EEG dataset
channel_names = [f'E{c}' for c in range(1, 129)]
channel_names.append('Cz')
num_channels = len(channel_names)
num_samples = 10000
eeg_data = np.random.randn(num_channels, num_samples)
info = mne.create_info(channel_names, ch_types='eeg', sfreq=500)
info['line_freq'] = 60
raw = mne.io.RawArray(eeg_data, info)
raw.set_montage('GSN-HydroCel-129')

# the montage associated with a raw object
montage_from_raw = raw.get_montage()
# the montage from a standard montage label
montage_from_standard = mne.channels.make_standard_montage('GSN-HydroCel-129')
# the channel positions, the same values as raw.info['chs']
channel_positions = raw._get_channel_positions()

# get position matrices from the montage objects
montage_from_raw_positions = extract_positions_from_montage(montage_from_raw)
montage_from_standard_positions = extract_positions_from_montage(montage_from_standard)

# get the distance between electrodes for all three variations
montage_from_raw_distances = get_channel_distances(montage_from_raw_positions)
montage_from_standard_distances = get_channel_distances(montage_from_standard_positions)
channel_positions_distances = get_channel_distances(channel_positions)

max_std_to_raw_montage_diff = np.max(np.abs(montage_from_raw_distances - montage_from_standard_distances))
max_raw_montage_to_channel_pos_diff = np.max(np.abs(montage_from_raw_distances - channel_positions_distances))


```

**Comment by yanbin-niu** [comment]
Hey @DMRoberts, I have had a crazy week and just got time to use your code to test with the real data.

I run your testing code with our real raw data. You are absolutely right that in terms of the distance calculation, the difference can be totally ignored. So, correspondingly, I have edited the code in this PR to read the locations by `raw._get_channel_positions()`. 

The only remaining minor thing is: if a use never sets the montage either because they forget or because they use the digitized locations, we might not have to * 100 to convert m into cm. For example, our example data's the default unit (before setting montage) is cm. Though I do not think this matters much for the FASTER (in which the distances were used in `polyval`), it does matter for whether we should use 9.5 or 0.095 as the cut-off point for region identification in the ADJUST. 

So, I also added the code:
```
    # if the max value is smaller than .2 (20cm), the unit should be 'm' and should be converted into 'cm'
    if np.max(np.abs(cartesian_locations)) < .2:
        cartesian_locations = cartesian_locations * 100
```

0.2 is a random number that I think normally should not be exceeded with the m unit. (The maximum value in our data is 0.132).

Huge thanks again @DMRoberts

**Comment by yanbin-niu** [comment]
@DMRoberts The remaining issue is to decide on whether the PCA mean and pre_whitener need to be incorporated. https://github.com/NDCLab/pepper-pipeline/issues/259

Your last comment on the issue is the code that is used when the data is reassembled after removing an independent component.  
https://github.com/mne-tools/mne-python/blob/51f19b5a16e900d0b1944af16255aaa677069e60/mne/preprocessing/ica.py#L1691

I took a closer look at this. Basically, the whole process is:  
```
raw_prewhiten = raw / ica.pre_whitener_ - ica.pca_mean_[:, None]

unmixing = np.dot(ica.unmixing_matrix_, ica.pca_components_)
mixing = (ica.pca_components_.T) @ ica.mixing_matrix_
proj_mat = np.dot(mixing, unmixing)

raw_proj = np.dot(proj_mat, raw_prewhiten)

# restore scaling
raw_result = (raw_proj + ica.pca_mean_[:, None]) * ica.pre_whitener_
```

And finally we got the result data. 

But the FASTER needs the activation matrix and the mixing matrix (before removing any component). Early on, I think we all agree on that `ICA.get_sources()` can give us the activation matrix. So the issue is the mixing matrix - whether incorporate  the PCA mean and pre_whitener into `ICA.get_components()`.

As I said before, I can not get the raw data by multiplying the matrix of ICA.get_components() by the matrix of ICA.get_sources(). So, I have tried to manually compute raw data from the activation matrix (`ICA.get_sources()`). Long story short - if I incorporate the PCA mean and pre_whitener, I actually can get the raw data.

Here is the code for `ica.get_sources(raw)`  -- so I just did the inverse computation:
https://github.com/mne-tools/mne-python/blob/51f19b5a16e900d0b1944af16255aaa677069e60/mne/preprocessing/ica.py#L691

The full testing code is:

```
import mne.io
import numpy as np

# import raw data
raw_path = 'raw_cropped_filtered.set'
raw = mne.io.read_raw_eeglab(raw_path)
raw.set_montage('GSN-HydroCel-129')

raw.info['bads'].extend(['E8', 'E17', 'E25', 'E62', 'E62', 'E72', 'E76'])
ref_elec_name = 'E129'

# prep for ica - make a copy
raw_filtered_1 = raw.copy()

# remove reference channel
raw_filtered_1.drop_channels(ref_elec_name)

# High-pass with 1. Hz cut-off is recommended for ICA
raw_filtered_1 = raw_filtered_1.load_data().filter(l_freq=1, h_freq=None)

# epoch with arbitrary 1s
epochs_prep = mne.make_fixed_length_epochs(raw_filtered_1, duration=1.0, preload=True, overlap=0.0)

# number of epeochs pre-rejection
epochs_original = epochs_prep.__len__()

# detect epochs - that are excessively “noisy” for any channel
reject_criteria = dict(eeg = 1000e-6)       # 1000 µV
epochs_prep.drop_bad(reject = reject_criteria)

# compute the number of epochs after removal
epochs_bads_removal = epochs_prep.__len__()
epochs_bads = epochs_original - epochs_bads_removal

# ica
method = 'picard'
max_iter = 'auto'
fit_params = dict(ortho=False, extended=True)
ica = mne.preprocessing.ICA(n_components=None,
                            method=method,
                            max_iter=max_iter,
                            fit_params=fit_params,
                            random_state=4)
ica.fit(epochs_prep)

# prepare raw data array - need to remove bad channels and the reference for matrix computation
raw_cled = raw.copy()
bad_chans = raw_cled.info['bads']

# remove bad channels and the reference
raw_cled.drop_channels(bad_chans)
raw_cled.drop_channels('E129')
raw_cled_arr = raw_cled.get_data()

# get activation matrix
icaact = ica.get_sources(raw).get_data()

# here is how to get raw data by ica activation matrix
(np.dot(ica.get_components(), icaact) + ica.pca_mean_[:, None])*ica.pre_whitener_ 
```

It's long, but only the last line is noteworthy. The reminding part is doing preparation for the ica which I cope and paste from this PR. In short, by `(np.dot(ica.get_components(), icaact) + ica.pca_mean_[:, None])*ica.pre_whitener_ ` we can get exact raw data. However, even with knowing all this, it’s still not straightforward to compute a matrix that implies `ica.get_components()` to get the raw data. (since it's like: （MxA - a）* b = R, I did not figure out a way to compute a matrix, say C, so that MxC = R ) Does this make sense? 

An alternative idea is: since the code you mentioned actually does restore the scaling (https://github.com/mne-tools/mne-python/blob/51f19b5a16e900d0b1944af16255aaa677069e60/mne/preprocessing/ica.py#L1691), I was wondering, maybe for activation matrix, we can simply get by `np.dot(np.linalg.inv(ica.get_components()), raw)` rather than using `ica.get_source()`. So this new activation matrix does not involve the PCA mean and pre_whitener. (`ica.get_source()` involves incorporating the PCA mean and pre_whitener first. )

I am not sure whether I am clear here. Happy to clarify if anything is unclear.

**Comment by georgebuzzell** [comment]
Scheduled meeting with @yanbin-niu for Monday at 9 am to discuss PR.

**Comment by DMRoberts** [comment]
Hey @yanbin-niu on the following, and your associated check for the scale of the values:

> The only remaining minor thing is: if a use never sets the montage either because they forget or because they use the digitized locations, we might not have to * 100 to convert m into cm. For example, our example data's the default unit (before setting montage) is cm.

I'm not 100% sure, but I believe that once the locations are loaded into MNE, they are automatically converted to meters, and that we can assume that the values present in the MNE data structures are in meters without a range check. For example, although the .SFP file we are referencing is in centimeters, I believe once the values are in the MNE data structures they are instead in meters.

**Comment by yanbin-niu** [comment]
@DMRoberts Thanks for the comment. You are right, I checked this. I just notice that I was using `read_raw_eeglab(raw_path)` for reading the raw data that I was saved from the eeglab after running ica. So I guess it keeps eeglab's unit (centimeter) while using `read_raw_eeglab(raw_path)`. But in the `mne_bids.read_raw_bids(bids_path)` method, it is in meters. I will do a quick edit on the code to remove the checking. Thanks again!

**Comment by DMRoberts** [comment]
@yanbin-niu in the ICA matrix questions, I think you are correct that ica.get_sources(raw) returns the 'activation matrix', or essentially a time series of component activations.

In the above example, the same number of PCA components as EEG electrodes are being submitted to the ICA. Do you maintain equivalence with the raw data when reducing the number of PCA components, for example by setting n_components to an integer value. In my initial condition I don't seem to get the original data back when the PCA components is less than the number of electrodes, so I think there may possibly be an additional step missing.

```
ica = mne.preprocessing.ICA(n_components=20,
                            method=method,
                            max_iter=max_iter,
                            fit_params=fit_params,
                            random_state=4)
```

**Comment by DMRoberts** [comment]
@yanbin-niu just following up my last comment, I think that `(np.dot(ica.get_components(), icaact) + ica.pca_mean_[:, None])*ica.pre_whitener_ ` does indeed return the raw channel space data, but only up to the number of PCA components submitted to the ICA. So for example, if you have 64 channels and 64 PCA components, that equation will return the channel space data. But if the number of PCA components < 64, I believe the result will diverge. One way to see this is to set the `n_components` when creating the ICA object to 2 and plot the reconstructed signal against the original data. In MNE, I believe that when transforming back to channel space data from ICA space, the PCA components that weren't submitted to ICA are added back : https://github.com/mne-tools/mne-python/blob/8aba865633e7a14c5bf382c31dc55e2fd07a7c3f/mne/preprocessing/ica.py#L1746 

We could identify how to add those PCA components back, though I actually think it may not be relevant here. I believe that the component matrix [channels x IC components] and source activations [IC components x time points] may be all that we need. I _believe_ those pre_whitener_ and pca_mean values are just the standard deviation and mean of each channel, respectively, prior to the PCA. If ADJUST just operates in the component space, those scaling factors may not influence the  components identified? Do you have a sense of how ADJUST is using the component matrix and source activations to identify components to remove?

**Comment by yanbin-niu** [comment]
Hey @DMRoberts, I think you are right that pre_whitener_ and pca_mean values are just the standard deviation and mean of each channel. So, now I realize that the pre_whitening step is merely standardizing? right? So, the ica steps in MNE are: 1) standardizing; 2) pca; 3) ica. 

`ica.get_sources(raw)` is actually computed by: 1) standardizing raw data; 2) pca; (passing the first `n_components` to ica); 3) ica. Now, I am thinking, maybe the better way to get the activation matrix is to: revert the standardization of `ica.get_sources(raw)`? what do you think about this? Coz the code you sent early on -- the `_pick_sources` method, also reverts the standardization at the end.
https://github.com/mne-tools/mne-python/blob/51f19b5a16e900d0b1944af16255aaa677069e60/mne/preprocessing/ica.py#L1691


Or, as you said, the standardization probably does not matter at all. All we need is `ica.get_components()` and `ica.get_sources(raw)`.

**Comment by yanbin-niu** [comment]
@DMRoberts Here is what I know about the ADJUST:

1) First, the mixing matrix is normalized (`ScalingFactor=norm(topografie(i,:))`); Then this `ScalingFactor` is applied to the activation matrix as well;

2) Feature value - GD (Generic Discontinuity) is computed from the normalized mixing matrix: the normalized mixing matrix is weighted based on the distances of 10 nearest channels. Then a difference is calculated - `abs(mixingmatrix_normed(ic,elec)-mean(weight.* mixingmatrix_normed(ic,ten_nearest_elec)'))`;

3) Feature value - SED (Spatial Eye Difference) is computed from the normalized mixing matrix: 1) compute the mean of `mixingmatrix_normed` in left area and the right area; 2) the abs difference between the left and right;

4) Feature value - SAD (Spatial Average Difference) is computed from the normalized mixing matrix: 1) get the mean of `mixingmatrix_normed` in front area and the back area; 2) the difference between the abs means of the front and back areas is computed; 3) compute the variances of `mixingmatrix_normed` in front area and the back area respectively; 4) compute the difference between front area variance and back area variance;

5) the kurtosis and variance of normed activation matrix are computed; followed by some mean and max calculations, like mean_kurtosis, mean_variance, etc..

6) compute thresholds of feature values, from which four kinds of artifacts are identified.

**Comment by yanbin-niu** [comment]
> ica.get_sources(raw) is actually computed by: 1) standardizing raw data; 2) pca; (passing the first n_components to ica); 3) ica. Now, I am thinking, maybe the better way to get the activation matrix is to: revert the standardization of ica.get_sources(raw)? what do you think about this? Coz the code you sent early on -- the _pick_sources method, also reverts the standardization at the end.

now I think it does not make sense or it does not make any difference, since the mixing matrix (`ica.get_components()`) operates on the standardized raw data, we should put the activation matrix on the page too. Right? @DMRoberts

**Comment by georgebuzzell** [comment]
@yanbin-niu and I met this morning to review the current PR, outstanding issues, and next steps.

Currently, the code in this PR is shown to match EEGLAB-Faster when the same activation and transformation matrices (and channel locations in spherical coordinates) are exported from EEGLAB and brought into python/mne. That is, all code  in the MNE-Faster implementation by @yanbin-niu works the same as EEGLAB-faster in terms of identifying bad ica components. Thus, this PR is being approved and merged in.

However, the outstanding issue is to confirm that the same/similar activation and transformation matrices can be generated in mne-python. Towards this end, @yanbin-niu will creat a new issue, then PR, to demonstrate that when the same ICA algorithem (infomax) is used in EEGLAB and MNE, and the random seed is set to be the same, then the same/similar activation and transformation matrices are generated in mne-python as eeglab. Note that identical activation and transformation matrices may not be generated due to rounding errors. However, the confirmation of "good enough" is that plots of each looks very similar. Additionally, running the mne-adjust code on the activation and transformation matrices generated by mne should yield identification of the same bad components as those identified by running ica and adjust in eeglab. However, these additional checks are beyond the scope of the current issue/pr, thus, the current pr is being approved.

@DMRoberts @F-said

**Review by georgebuzzell — APPROVED** [review]
@yanbin-niu and I met this morning to review the current PR, outstanding issues, and next steps.

Currently, the code in this PR is shown to match EEGLAB-Faster when the same activation and transformation matrices (and channel locations in spherical coordinates) are exported from EEGLAB and brought into python/mne. That is, all code in the MNE-Faster implementation by @yanbin-niu works the same as EEGLAB-faster in terms of identifying bad ica components. Thus, this PR is being approved and merged in.

However, the outstanding issue is to confirm that the same/similar activation and transformation matrices can be generated in mne-python. Towards this end, @yanbin-niu will creat a new issue, then PR, to demonstrate that when the same ICA algorithem (infomax) is used in EEGLAB and MNE, and the random seed is set to be the same, then the same/similar activation and transformation matrices are generated in mne-python as eeglab. Note that identical activation and transformation matrices may not be generated due to rounding errors. However, the confirmation of "good enough" is that plots of each looks very similar. Additionally, running the mne-adjust code on the activation and transformation matrices generated by mne should yield identification of the same bad components as those identified by running ica and adjust in eeglab. However, these additional checks are beyond the scope of the current issue/pr, thus, the current pr is being approved.

@DMRoberts @F-said

**Comment by yanbin-niu** [comment]
The remaining work / outstanding issue will be discussed in https://github.com/NDCLab/pepper-pipeline/issues/259

**Pull request merged**
